// GENERATED by scripts/build-content.mjs from /content. Edit the markdown, then run `npm run content`.
export const FAMILIES = [
 {
  "base": "Old Money",
  "name": "Ancient House",
  "flavour": "Centuries of land and tradition"
 },
 {
  "base": "Peerage",
  "name": "High House",
  "flavour": "Holds a seat and a title among the great Houses"
 },
 {
  "base": "New Money",
  "name": "Counting-House",
  "flavour": "Trade and industry, rich but not welcome"
 },
 {
  "base": "Humble Origins",
  "name": "Lesser Line",
  "flavour": "Poor branch of a good name"
 },
 {
  "base": "Clergy",
  "name": "Temple House",
  "flavour": "Moral weight, modest purse"
 },
 {
  "base": "Military",
  "name": "Banner House",
  "flavour": "Sworn swords, honour and discipline"
 },
 {
  "base": "Ill-Reputed",
  "name": "Shadowed House",
  "flavour": "A scandal sits over every dinner"
 },
 {
  "base": "Foreign",
  "name": "Far-Court",
  "flavour": "From another realm, culture or plane"
 }
];
export const DESIRES = [
 {
  "n": 1,
  "kind": "Basic",
  "age": false,
  "title": "Redeem a disgrace",
  "text": "Win back a former friend's forgiveness and your good name. One rash act cost you both. Create and spread a rumour about what you did. Start with +Tag and +Insp.",
  "hook": "The friend is in danger, and only you can help."
 },
 {
  "n": 2,
  "kind": "Complex",
  "age": true,
  "title": "Be acknowledged",
  "text": "Make a powerful parent recognise you publicly as their child and heir to the House. They refused you from the cradle. You will use charm, favours or worse.",
  "hook": "Prove your lineage through a trial, a relic or a long-lost witness."
 },
 {
  "n": 3,
  "kind": "Basic",
  "age": false,
  "title": "Keep your options open",
  "text": "Receive or make at least two successful proposals from eligible suitors. Marry one and quietly release the other.",
  "hook": "A suitor's family has dungeons, debts or enemies attached."
 },
 {
  "n": 4,
  "kind": "Complex",
  "age": false,
  "title": "Take revenge on your rival",
  "text": "They took what you loved. Work with their player to decide what it was. You have waited a long time for this.",
  "hook": "The stolen thing is an object or place you can go and take back."
 },
 {
  "n": 5,
  "kind": "Basic",
  "age": false,
  "title": "Solve a debt secretly",
  "text": "Come into substantial wealth fast, while keeping your reputation spotless. Your debts are severe and your creditors are patient but not kind.",
  "hook": "A treasure or contract could settle the debt, if you can reach it."
 },
 {
  "n": 6,
  "kind": "Basic",
  "age": false,
  "title": "Take your sibling's seat",
  "text": "Convince your House to disinherit your elder sibling and name you heir. You need one scandal or one mistake. Create a parent as a mandatory connection.",
  "hook": "Find the proof, or manufacture the incident."
 },
 {
  "n": 7,
  "kind": "Basic",
  "age": false,
  "title": "Play matchmaker",
  "text": "Orchestrate at least one marriage between people of your choosing. After the first session, name two potential couples and tell the DM. Succeed with one or both.",
  "hook": "A couple's families are feuding, or the match needs a rare gift or blessing."
 },
 {
  "n": 8,
  "kind": "Complex",
  "age": false,
  "title": "Restore the family name",
  "text": "Ten years ago your House broke an oath in a scandal that shook the realm, and fled. You are back to claim your place. Not everyone is pleased. Public knowledge: the scandal. Create and spread two negative rumours about your House.",
  "hook": "Make amends for the broken oath, or find out what really happened."
 },
 {
  "n": 9,
  "kind": "Basic",
  "age": false,
  "title": "Earn consent",
  "text": "Raise your beloved's reputation, then win your parent's permission to marry. Only an impeccable name will do. Create a parent as a mandatory connection.",
  "hook": "Your beloved's reputation needs a heroic deed or a clearing of old charges."
 },
 {
  "n": 10,
  "kind": "Basic",
  "age": false,
  "title": "Be loved for yourself",
  "text": "You have just inherited a vast fortune: a hoard, a title or a magical estate. Marry someone who loves you without knowing about it.",
  "hook": "The inheritance has strings: guardians, a curse, or claimants."
 },
 {
  "n": 11,
  "kind": "Basic",
  "age": false,
  "title": "Guard your sibling",
  "text": "Your younger sibling is naive and vulnerable. Protect them from every ill and choose who they marry. After the first session, name the match you want.",
  "hook": "A dangerous suitor, a kidnapper or a curse stalks them."
 },
 {
  "n": 12,
  "kind": "Complex",
  "age": false,
  "title": "The double game",
  "text": "Appear to court the partner your wealthy aunt chose for you, while secretly becoming engaged to the one you love. She is wealthy, dying and watching. Create your aunt as a mandatory connection.",
  "hook": "The aunt's estate has a guardian, a will-ward or a rival claimant."
 },
 {
  "n": 13,
  "kind": "Basic",
  "age": false,
  "title": "Claim what's yours",
  "text": "You were disowned for something shocking three years ago. You are back to claim your inheritance. Create and spread a rumour about what you did. Start with +Tag and +Insp. Public knowledge: you were disinherited. If you lack the parent relationship card, create a parent as a mandatory connection.",
  "hook": "Win your House's trust with a deed or a returned relic."
 },
 {
  "n": 14,
  "kind": "Basic",
  "age": false,
  "title": "Turn the tables",
  "text": "You lived in an enemy's shadow while they got every advantage. Now turn their connections against them.",
  "hook": "Their allies have secrets you can find in places others avoid."
 },
 {
  "n": 15,
  "kind": "Complex",
  "age": false,
  "title": "Break the engagement",
  "text": "Your reckless family ruined itself, and your father arranged your engagement to a rich stranger to avoid selling the estate. Fix the family's finances, then call it off. Public knowledge: you are engaged.",
  "hook": "Save the family with a quest, a sale, or a marriage for someone else."
 },
 {
  "n": 16,
  "kind": "Basic",
  "age": false,
  "title": "Marry your secret betrothed",
  "text": "You and another were secretly engaged three years ago. Their feelings are fading, and the marriage is also your only route to a rank you could never reach.",
  "hook": "Win them back through a grand gesture, or find out why they've cooled."
 },
 {
  "n": 17,
  "kind": "Basic",
  "age": false,
  "title": "Outshine your cousin",
  "text": "Beat your perfect cousin in every contest and win your uncle's inheritance, the seat of the House and the magic that comes with it. Create your uncle as a mandatory connection.",
  "hook": "The uncle sets trials, and your cousin is ahead."
 },
 {
  "n": 18,
  "kind": "Basic",
  "age": false,
  "title": "Rekindle",
  "text": "Five years ago, you broke a secret engagement under pressure. Find out if they still love you, and re-establish the engagement.",
  "hook": "Their circumstances have changed, perhaps into danger."
 },
 {
  "n": 19,
  "kind": "Complex",
  "age": false,
  "title": "Divide them",
  "text": "The one you love has fallen for someone else. You have waited too long. Break up the pair by any means. If your relationship card is Rival, decide who your love is.",
  "hook": "The paramour has a vulnerability, an enemy or a secret."
 },
 {
  "n": 20,
  "kind": "Basic",
  "age": false,
  "title": "Impress your patron",
  "text": "Marry in a way your patron approves, to keep their support. You owe them your career. Show this card to your patron.",
  "hook": "The patron's approval comes with a task."
 },
 {
  "n": 21,
  "kind": "Basic",
  "age": true,
  "title": "Marry your child well",
  "text": "Marry your child to someone extremely wealthy or of the High Houses. They are your best asset and you intend to use them.",
  "hook": "The target match is protected, secret or unwilling."
 },
 {
  "n": 22,
  "kind": "Complex",
  "age": false,
  "title": "End the feud",
  "text": "Two Houses have been at war since your grandparents' day, and it is costing both of them their futures. End it through marriage or inheritance. Public knowledge: the feud, and who it is between.",
  "hook": "The feud started over a lost relic, a death or a broken pact."
 }
];
export const RELATIONSHIPS = [
 {
  "n": 23,
  "public": {
   "title": "Best of Friends",
   "text": "Close companions."
  },
  "private": {
   "title": "",
   "text": "Same, and ready to help with each other's plans."
  }
 },
 {
  "n": 24,
  "public": {
   "title": "Former Friends",
   "text": "The giver's cruelty ended it."
  },
  "private": {
   "title": "",
   "text": "The giver wronged the taker deeply."
  }
 },
 {
  "n": 25,
  "public": {
   "title": "Friends",
   "text": "Long acquaintance, occasional visits."
  },
  "private": {
   "title": "Old Flames",
   "text": "They had a romance once. The spark remains."
  }
 },
 {
  "n": 26,
  "public": {
   "title": "Old Family Friends",
   "text": "Their Houses were close."
  },
  "private": {
   "title": "Parent & Child",
   "text": "The giver is the taker's illegitimate child, rejected from birth."
  }
 },
 {
  "n": 27,
  "public": {
   "title": "Siblings",
   "text": "The giver decides who is older."
  },
  "private": {
   "title": "",
   "text": "Same."
  }
 },
 {
  "n": 28,
  "public": {
   "title": "Rivals",
   "text": ""
  },
  "private": {
   "title": "",
   "text": "A trivial rivalry for the taker, a bitter one for the giver."
  }
 },
 {
  "n": 29,
  "public": {
   "title": "Relation",
   "text": "Cousin, aunt, uncle, niece or nephew. The giver decides."
  },
  "private": {
   "title": "",
   "text": "Same."
  }
 },
 {
  "n": 30,
  "public": {
   "title": "Object of Affection",
   "text": "The giver is clearly in love with the taker."
  },
  "private": {
   "title": "",
   "text": "Whether the taker returns it is up to them."
  }
 },
 {
  "n": 31,
  "public": {
   "title": "Acquaintances",
   "text": "Met during a Season."
  },
  "private": {
   "title": "Secret Betrothed",
   "text": "Engaged for years against a family's wishes. The taker is higher in rank or richer and is wavering."
  }
 },
 {
  "n": 32,
  "public": {
   "title": "Intended",
   "text": "Publicly engaged or pact-bound."
  },
  "private": {
   "title": "",
   "text": "Same."
  }
 },
 {
  "n": 33,
  "public": {
   "title": "Parent & Child",
   "text": "The giver is parent or guardian."
  },
  "private": {
   "title": "",
   "text": "Same."
  }
 },
 {
  "n": 34,
  "public": {
   "title": "Child & Parent",
   "text": "The giver is child or ward."
  },
  "private": {
   "title": "",
   "text": "Same."
  }
 },
 {
  "n": 35,
  "public": {
   "title": "Patron",
   "text": "The taker is the giver's patron."
  },
  "private": {
   "title": "",
   "text": "For now. What the giver owes is revealed in play."
  }
 },
 {
  "n": 36,
  "public": {
   "title": "Mentor",
   "text": "The taker mentors the giver."
  },
  "private": {
   "title": "",
   "text": "Same."
  }
 }
];
export const CONNECTIONS = [
 {
  "n": 37,
  "name": "The Court Healer",
  "a": "Court healer-mage, trusted with the high table's secrets.",
  "b": "Hedge-healer, in debt, resents the nobility."
 },
 {
  "n": 38,
  "name": "The Temple Peacemaker",
  "a": "Hearth-temple peacemaker. Cannot rest while two people are at odds.",
  "b": "Retired adventurer turned innkeeper. Owns half the high street."
 },
 {
  "n": 39,
  "name": "The Duelist",
  "a": "Arena duelist with fans and gambling debts.",
  "b": "Disgraced knight, charming, one scandal from ruin."
 },
 {
  "n": 40,
  "name": "The Young Prodigy",
  "a": "Teenage heir who hides in libraries and knows every secret.",
  "b": "Teenage prodigy with a bonded familiar. Their House defers to them."
 },
 {
  "n": 41,
  "name": "The Matchmaker",
  "a": "Matchmaker to the courts. Spouse always away at sea.",
  "b": "Seer whose predictions quietly steer marriages."
 },
 {
  "n": 42,
  "name": "The Halfling Confidant",
  "a": "Halfling clerk of wards, meticulous, soft-hearted.",
  "b": "Halfling bard-preacher in love with their own voice."
 },
 {
  "n": 43,
  "name": "The Dandy",
  "a": "Dandy and wit, scornful of work.",
  "b": "Second son dodging his family's demand to join the Banner Guard."
 },
 {
  "n": 44,
  "name": "The Society Gossip",
  "a": "Gnome gossip-columnist and social chair.",
  "b": "Newly rich mother of three. Her children are the way to her heart."
 },
 {
  "n": 45,
  "name": "The Newly Wealthy",
  "a": "Recently wealthy, kind and naive.",
  "b": "Inherited a barony, and suspects every suitor."
 },
 {
  "n": 46,
  "name": "The Counting-House Master",
  "a": "Counting-House master who hides his humble origins.",
  "b": "Ruthless financier behind a gentle mask."
 },
 {
  "n": 47,
  "name": "The High House Socialite",
  "a": "High House socialite, very rich.",
  "b": "Social tactician, one step ahead of you."
 },
 {
  "n": 48,
  "name": "The Registry Archivist",
  "a": "Archivist of the Royal Registry. Knows who is legitimate.",
  "b": "Quietly sells \"improved\" pedigrees."
 },
 {
  "n": 49,
  "name": "The Dwarf Heiress",
  "a": "Dwarf heiress, sharp-tongued secret romantic.",
  "b": "Heartbroken after a broken betrothal. The scandal lingers."
 },
 {
  "n": 50,
  "name": "The Cartographer",
  "a": "Wandering cartographer hired by Houses to settle borders.",
  "b": "Smuggler-pilot who carries nobles' secrets between cities."
 },
 {
  "n": 51,
  "name": "The Tax Assessor",
  "a": "Royal tax assessor, incorruptible and dreaded at dinner.",
  "b": "Assessor in debt, quietly open to bribes."
 },
 {
  "n": 52,
  "name": "The Artist-Enchanter",
  "a": "Widow whose husband died in a griffon race.",
  "b": "Artist-enchanter who hosts bewildering salons."
 },
 {
  "n": 53,
  "name": "The Royal Champion",
  "a": "Retired royal champion, a living legend bored in peacetime.",
  "b": "Aging champion hiding a failing sword arm."
 },
 {
  "n": 54,
  "name": "The Magistrate",
  "a": "Circuit judge of the Concord courts, fair and stern.",
  "b": "Judge owned by a House's patronage."
 },
 {
  "n": 55,
  "name": "The Adventurer",
  "a": "Short-tempered adventurer, fiercely independent.",
  "b": "Wanderer who craves travel and has no means."
 },
 {
  "n": 56,
  "name": "The Philanthropist",
  "a": "Self-made philanthropist, generous with second chances.",
  "b": "Risen from humble origins, advises others on how."
 },
 {
  "n": 57,
  "name": "The Dowager",
  "a": "Formidable matriarch, champion of friends and terror of enemies.",
  "b": "Widow who gives advice as constructive insults."
 },
 {
  "n": 58,
  "name": "The Gossip-Broker",
  "a": "Calculating gossip-broker.",
  "b": "Famed illusionist-actress with a past scandal."
 },
 {
  "n": 59,
  "name": "The Fae Envoy",
  "a": "Fae envoy bound by treaty, delighted by human manners.",
  "b": "Fae bargain-broker who trades in names and favours."
 },
 {
  "n": 60,
  "name": "The Construct Servant",
  "a": "Construct servant of a House for centuries. Remembers everything.",
  "b": "Newly awakened construct questioning its bound service."
 },
 {
  "n": 61,
  "name": "The Undertaker",
  "a": "Courteous undertaker-necromancer who tends the House dead and their secrets.",
  "b": "Grave-warden with a grudge against a House."
 },
 {
  "n": 62,
  "name": "The Falconer",
  "a": "Falconer and spy for the Crown's Eyes.",
  "b": "Falconer for hire who sells the same to rival Houses."
 },
 {
  "n": 63,
  "name": "The Dragon-Warden",
  "a": "Dragon-warden who manages a House's dragon and its temper.",
  "b": "Dragon-heir whose bonded dragon is rumoured to be ill."
 },
 {
  "n": 64,
  "name": "The Schemer",
  "a": "Vengeful and petty. Switches sides for a price.",
  "b": "Scheming ruiner of reputations. Never forgives."
 },
 {
  "n": 65,
  "name": "The Wealthy Peer",
  "a": "Wealthy peer, stern and businesslike.",
  "b": "Peer in decline, softens around children."
 },
 {
  "n": 66,
  "name": "The Reserved Heir",
  "a": "Reserved and anxious. Secretly writes financial pamphlets under a pen name.",
  "b": "Gentle, runs a parent's business, resigned to a quiet single life."
 }
];
