// Starting names for the towns, forts and landmarks drawn on the Corvane picture: [column, row, name].
export const PLACE_NAMES = [
  [10, 9, 'Concordia'],
  [15, 2, 'Castellane'],
  [11, 3, 'Wrenford'],
  [13, 5, 'Thornwick'],
  [16, 9, 'Harrowmere'],
  [4, 10, 'Veilspire'],
  [15, 12, 'Port Calder'],
  [8, 13, 'Amberleigh'],
  [11, 13, 'Quillhaven'],
  [10, 2, 'Highwatch'],
  [7, 3, 'Cragmoor Keep'],
  [16, 3, 'Silverfall Keep'],
  [8, 6, 'Saltmere Watch'],
  [7, 10, 'Westergate'],
  [8, 9, 'The Oathgate'],
  [6, 14, 'Old Heronbridge'],
  [10, 14, 'Pilgrim’s Rest'],
];
