// Regenerates lib/rules-data.js and lib/deck-data.js from the markdown in /content.
// Run with: npm run content
import fs from 'node:fs';
import { marked } from 'marked';

marked.setOptions({ gfm: true, breaks: true });
const read = (f) => fs.readFileSync(new URL(`../content/${f}`, import.meta.url), 'utf8');
const write = (f, s) => fs.writeFileSync(new URL(`../lib/${f}`, import.meta.url), s);
const banner = '// GENERATED by scripts/build-content.mjs from /content. Edit the markdown, then run `npm run content`.\n';

// ---------- Rules book ----------
{
  const md = read('rules.md');
  const parts = md.split(/^## /m);
  const intro = parts.shift().replace(/^# .*\n/, '').replace(/^---\s*$/m, '').trim();
  const title = (md.match(/^# (.*)$/m) || [, 'Rules'])[1];
  const chapters = [];
  for (const p of parts) {
    const nl = p.indexOf('\n');
    const heading = p.slice(0, nl).trim();
    if (/^still open/i.test(heading)) continue; // design notes, not for the table
    const m = heading.match(/^(\d+)\.\s+(.*)$/);
    const body = p.slice(nl + 1).replace(/^---\s*$/gm, '').trim();
    chapters.push({ n: m ? Number(m[1]) : chapters.length + 1, title: m ? m[2] : heading, html: marked.parse(body) });
  }
  write('rules-data.js', `${banner}export const RULES_TITLE = ${JSON.stringify(title)};\nexport const RULES_INTRO = ${JSON.stringify(marked.parse(intro))};\nexport const CHAPTERS = ${JSON.stringify(chapters, null, 1)};\n`);
  console.log('rules chapters:', chapters.length);
}

// ---------- Deck ----------
{
  const md = read('setting-and-decks.md');
  const section = (re) => {
    const secs = md.split(/^## /m);
    return secs.find((s) => re.test(s.split('\n')[0])) || '';
  };
  const tableRows = (text) =>
    text
      .split('\n')
      .filter((l) => l.trim().startsWith('|'))
      .map((l) => l.trim().replace(/^\||\|$/g, '').split('|').map((c) => c.trim()))
      .filter((r) => r.length > 1 && !/^-+$/.test(r[0]) && !/^:?-+:?$/.test(r[0]))
      .slice(1); // header row
  const plain = (s) => s.replace(/\*\*/g, '').replace(/\*/g, '');
  // splits "**Title.** rest" into { title, text }
  const lead = (s) => {
    const m = s.match(/^\*\*(.+?)\.?\*\*\s*(.*)$/);
    return m ? { title: m[1].replace(/\.$/, ''), text: m[2] } : { title: '', text: plain(s) };
  };

  const families = tableRows(section(/^1\./)).map(([base, name, flavour, positive, negative, title]) => ({
    base, name: plain(name), flavour,
    positive: positive.split(',').map((t) => t.trim()),
    negative: negative.split(',').map((t) => t.trim()),
    title: title && title !== '-' ? title : '',
  }));

  const desires = [];
  const blocks = section(/^2\./).split(/\n\n+/);
  for (const b of blocks) {
    const lines = b.trim().split('\n');
    const h = lines[0].match(/^\*\*#(\d+)\.\s+(Basic|Complex)(, Age)?\.\s+(.+?)\.\*\*$/);
    if (!h) continue;
    const rest = lines.slice(1);
    const hook = rest.find((l) => l.startsWith('*Hook:*'));
    const body = rest.filter((l) => !l.startsWith('*Hook:*'));
    desires.push({
      n: Number(h[1]), kind: h[2], age: Boolean(h[3]), title: h[4],
      text: body.join(' '), hook: hook ? hook.replace('*Hook:*', '').trim() : '',
    });
  }

  const relationships = tableRows(section(/^3\./)).map(([n, pub, priv]) => ({
    n: Number(n), public: lead(pub), private: lead(priv),
  }));

  const connections = tableRows(section(/^4\./)).map(([n, name, a, b]) => ({
    n: Number(n), name, a, b,
  }));

  const counts = { families: families.length, desires: desires.length, relationships: relationships.length, connections: connections.length };
  if (desires.length !== 22 || relationships.length !== 14 || connections.length !== 30 || families.length !== 8) {
    console.error('Unexpected card counts', counts);
    process.exit(1);
  }
  write('deck-data.js', `${banner}export const FAMILIES = ${JSON.stringify(families, null, 1)};\nexport const DESIRES = ${JSON.stringify(desires, null, 1)};\nexport const RELATIONSHIPS = ${JSON.stringify(relationships, null, 1)};\nexport const CONNECTIONS = ${JSON.stringify(connections, null, 1)};\n`);
  console.log('deck:', counts);
}
